# Generated by Django 4.2.1 on 2023-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='person_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг клиента'),
        ),
    ]
